security:
    encoders:
        App\Security\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Security\User
                property: email

    firewalls:
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_home
